runtime: python39  # Specifies the Python version

entrypoint: gunicorn -b :$PORT app:app  # Correctly points to your Flask app's WSGI object

env: standard  # Uses the standard environment which is optimal for applications that require scaling and automatic management

instance_class: F1  # Specifies the instance class, F1 is a smallest class suitable for low traffic

# Ensures all URLs are handled by the application; this config serves all traffic through HTTPS
handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3  # Configures auto-scaling with CPU utilization targets and instance limits

env_variables:
  # Replace 'your_username', 'your_password', 'your_db_hostname', and 'your_database_name' with real values
  DATABASE_URL: "postgresql://retool:ERcUMAHu3B0k@ep-ancient-wildflower-190949.us-west-2.retooldb.com/retool?sslmode=require"